### PR TITLE
XYColour Working Full!

### PR DESCRIPTION
**Pull request by gr812b**
Fixing XYColour functionality, as it broke during various refactors

### CODE REVIEW

**Review by camdnnn — CHANGES_REQUESTED** [review]
don't work

**Comment by gr812b** [comment]
Did we restart the backend? I think it work @camdnnn

**Comment by camdnnn** [comment]
> Did we restart the backend? I think it work @camdnnn 

I haven't actually tested it myself

**Comment by gr812b** [comment]
> > Did we restart the backend? I think it work @camdnnn
> 
> I haven't actually tested it myself

Can you quickly?

**Review by camdnnn — APPROVED** [review]
:schit:

**Pull request merged**
